AUGMENTATION: True
IMAGE_SIZE: [224, 224]              
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 1
FINE_TUNE_EPOCHS: 1
CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.001 
FINE_TUNE_LEARNING_RATE: 0.00001 
DROPOUT: 0.5                 
