artifacts_root: artifacts

# Stage 01: Data Ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1xRFDD7wuShMe-Uq9Y_PjK-sEHT9JswHW/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/Lungs_Disease_Classification

# Stage 02: Prepare Base Model
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

# Stage 03: Training
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

# Stage 04: Evaluation
evaluation:
  path_of_model: artifacts/training/model.h5
  mlflow_uri: https://dagshub.com/Viswa-Prakash/MLOPs_Lung_Disease_Classification.mlflow
  experiment_name: "lung-disease-eval"
  registered_model_name: "LungDiseaseClassifier"
  dagshub_repo_owner: "Viswa-Prakash"
  dagshub_repo_name: "MLOPs_Lung_Disease_Classification"

# Stage 05: Model Pusher
model_pusher:
  bucket_name: mlops-image-classifier-models
  s3_model_path: model.h5
  local_model_path: artifacts/training/model.h5
