artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://drive.google.com/file/d/1xRFDD7wuShMe-Uq9Y_PjK-sEHT9JswHW/view?usp=sharing
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion